import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8')
const quoteStyles = await readFile(new URL('../quotes-preview.css', import.meta.url), 'utf8')
const whatsappStyles = await readFile(new URL('../whatsapp-inbox.css', import.meta.url), 'utf8')
const app = await readFile(new URL('../app.js', import.meta.url), 'utf8')
const index = await readFile(new URL('../index.html', import.meta.url), 'utf8')
const clientUi = await readFile(new URL('../src/client-live-ui.js', import.meta.url), 'utf8')
const liveData = await readFile(new URL('../src/live-data.js', import.meta.url), 'utf8')

test('módulos usam superfícies verdes consistentes sem cores concorrentes', () => {
  assert.match(styles, /--module-soft:#edf5ee/)
  assert.match(styles, /\.module-panel,\.client-directory,\.attendance-list\{[\s\S]*border-radius:18px/)
  assert.match(styles, /\.attendance-summary>div,\.client-summary>div\{[\s\S]*background:var\(--module-soft\)/)
})

test('orçamentos, gestão e conversas seguem a mesma família visual', () => {
  assert.match(quoteStyles, /\.quote-preview-metrics > div\s*\{[\s\S]*background:\s*#edf5ee/)
  assert.doesNotMatch(quoteStyles, /\.quotes-preview-intro\{[^}]*linear-gradient/)
  assert.match(styles, /\.billing-summary>div\{[\s\S]*background:var\(--module-soft\)/)
  assert.match(whatsappStyles, /\.whatsapp-inbox\{[\s\S]*border-radius:18px/)
})

test('faturamento destaca o fluxo financeiro com card escuro e gráfico de recebimento', () => {
  assert.match(app, /billing-collection-card/)
  assert.match(app, /billing-ring/)
  assert.match(styles, /\.billing-collection-card\{[^}]*background:#2f3b32/)
  assert.match(styles, /\.billing-ring\{[^}]*conic-gradient/)
})

test('atendimentos usa a composição de painel da visão geral', () => {
  assert.match(styles, /\.attendances-shell\{display:grid;gap:22px/)
  assert.match(styles, /\.attendances-shell \.attendance-summary>div\{[^}]*background:#edf5ee/)
  assert.match(styles, /\.attendances-shell \.attendance-toolbar\{[\s\S]*border-radius:20px/)
  assert.match(styles, /\.attendances-shell \.attendance-list-heading\{[^}]*background:#edf5ee/)
})

test('atendimentos mostra o nome do responsável escolhido na ordem', () => {
  assert.match(app, /function openServiceByIndex\(rawIndex\)/)
  assert.match(app, /activeServiceIndex === index\) return/)
  assert.match(app, /stageIndex = serviceStates\[index\]\?\.stage \?\? 0/)
  assert.match(app, /document\.addEventListener\('click', \(event\) => \{[\s\S]*data-service-index\], \[data-dashboard-order\]/)
  assert.match(app, /function responsibleLabel\(item, index\)/)
  assert.match(app, /person\.id === responsible \|\| person\.full_name === responsible/)
  assert.match(app, /<span>\$\{responsibleLabel\(item, index\)\}<\/span>/)
  assert.match(app, /responsible\.textContent = responsibleLabel\(services\[index\], index\)/)
  assert.doesNotMatch(app, /<span>Equipe Atelier<\/span>/)
  assert.match(liveData, /supabase\.from\('profiles'\)\.select\('id, full_name, role'\)/)
  assert.match(liveData, /const responsibleProfile = teamProfiles\.find/)
  assert.match(liveData, /responsibleName: responsibleProfile\?\.full_name \|\| ''/)
})

test('agenda elimina o bege dos horários e usa a paleta verde do painel', () => {
  assert.match(styles, /\.main-content \.agenda-live-grid \.calendar-event-card\{[^}]*background:#edf5ee/)
  assert.match(styles, /\.main-content \.agenda-live-grid \.calendar-slot\{[^}]*background:#f8fcf9/)
})

test('agenda mantém separadores cinza neutro e não corta o dia ao passar o mouse', () => {
  assert.match(styles, /\.main-content \.agenda-live-grid\{[^}]*background:#e5e7e7[^}]*overflow:visible/)
  assert.match(styles, /\.main-content \.agenda-live-grid \.calendar-day:hover\{[^}]*transform:none/)
})

test('clientes e veículos substitui o bege pelos painéis verdes da visão geral', () => {
  assert.match(styles, /\.main-content \.client-summary>div\{[^}]*background:#edf5ee/)
  assert.match(styles, /\.main-content \.client-directory-heading\{[^}]*background:#edf5ee/)
  assert.match(styles, /\.main-content \.client-record:hover\{[^}]*background:#f8fcf9/)
})

test('catálogo de serviços usa verde-claro e ação de apagar textual', () => {
  assert.match(styles, /\.main-content \.service-price\{[^}]*background:#edf5ee/)
  assert.match(styles, /\.main-content \[data-service-delete\]:hover\{[^}]*background:transparent[^}]*color:#d32016!important/)
})

test('pós-venda mantém toda a área de acompanhamento em branco', () => {
  assert.match(styles, /\.main-content \.post-sale-metric\.today\{[^}]*background:#edf5ee/)
  const finalPostSalePanelRule = styles.lastIndexOf('.main-content .post-sale-panel{')
  assert.match(styles.slice(finalPostSalePanelRule), /^\.main-content \.post-sale-panel\{[^}]*background:#fff/)
  const finalClientCardRule = styles.lastIndexOf('.main-content .post-sale-client-card{')
  assert.match(styles.slice(finalClientCardRule), /^\.main-content \.post-sale-client-card\{[^}]*background:#fff/)
  assert.match(styles, /\.main-content \.post-sale-template-preview\{[^}]*background:#edf5ee/)
})

test('ação de apagar cliente tem coluna própria afastada da borda', () => {
  assert.match(styles, /\.main-content \.client-directory-heading,\.main-content \.client-record\{[^}]*grid-template-columns:2fr 1\.4fr 1fr 1\.3fr 92px/)
  assert.match(styles, /\.main-content \.client-record\{[^}]*padding-right:42px/)
})

test('ação de apagar cliente responde ao hover com vermelho mais forte', () => {
  assert.match(styles, /\.main-content \.client-record \[data-client-delete\]\{[^}]*border:0[^}]*background:transparent[^}]*color:#b54d45!important/)
  assert.match(styles, /\.main-content \.client-record \[data-client-delete\]:hover\{[^}]*background:transparent[^}]*color:#d32016!important/)
})

test('linguagem visual compartilhada evita controles quadrados e campos nativos quebrados', () => {
  assert.match(styles, /--radius-control:14px/)
  assert.match(styles, /\.app-shell>\.sidebar\{[^}]*background:#dceae1!important/)
  assert.match(styles, /\.main-content>\.topbar\{[^}]*background:#f5f8f5!important/)
  assert.match(styles, /\.app-shell>\.sidebar\.sidebar-olive\{[^}]*background:#2f3b32!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\{[^}]*background:transparent!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\{[^}]*height:58px!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\.topbar-collapsed\{[^}]*height:0!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\.topbar-collapsed\{[^}]*backdrop-filter:none!important/)
  assert.match(styles, /\.topbar-collapsed \.topbar-actions\{display:none!important/)
  assert.match(styles, /\.main-content\{background:#f3f0e8;color:#27332d/)
  assert.match(styles, /\.main-content \.module-panel,\.main-content \.panel,\.main-content \.table-panel\{background:#fffdf8/)
  assert.match(styles, /\.main-content \.primary-button\{background:#59684d/)
  assert.match(styles, /\.main-content \.dashboard-agenda-item\{border-radius:14px;margin:2px 0;padding:14px 12px/)
  assert.match(styles, /\.main-content \.dashboard-agenda-item:hover\{background:transparent;box-shadow:none;transform:translateY\(-2px\)/)
  assert.doesNotMatch(styles, /\.main-content \.dashboard-agenda-item:hover \.dashboard-arrow\{transform:translateX\(3px\)/)
  assert.match(styles, /\.main-content \.service-row\{min-height:72px;padding:18px 16px;border:1px solid var\(--line\);border-radius:18px;background:#fff/)
  assert.match(styles, /\.main-content \.service-row:hover\{background:#fff;transform:translateY\(-3px\);box-shadow:0 12px 26px rgba\(35,79,57,\.1\)/)
  assert.doesNotMatch(styles, /\.client-record:hover,.attendance-item:hover\{background:#f7fbf8;transform:translateX\(3px\)/)
  assert.match(styles, /\.main-content \.vehicle-mark\{width:40px;height:40px;border-radius:12px;background:#f4f0e6;border-color:#ded6c8/)
  assert.match(styles, /\.main-content \.vehicle-mark:before\{[^}]*background:transparent;border:1\.5px solid #59684d/)
  assert.match(styles, /\.main-content \.vehicle-mark:after\{left:11px;top:18px;width:18px;height:4px;border-radius:999px;background:#59684d;box-shadow:none/)
  assert.match(styles, /\.main-content \.vehicle-mark span\{left:15px;top:11px;width:9px;height:9px;border:1\.5px solid #59684d;border-radius:3px;transform:rotate\(45deg\)/)
  assert.match(app, /<button class="service-row" data-service-index="\$\{index\}"><div class="service-main">/)
  assert.match(styles, /\.main-content \.service-row\{grid-template-columns:1fr auto/)
  assert.match(styles, /\.main-content \.vehicle-mark\{display:none!important/)
  assert.match(styles, /\.main-content \.employee-dashboard-order\{grid-template-columns:minmax\(0,1fr\) auto 16px/)
  assert.match(quoteStyles, /\.quote-delete-button\s*\{[^}]*color:\s*#a24e4e/)
  assert.match(styles, /\.main-content \.service-row\{min-height:72px;padding:18px 16px/)
  assert.match(styles, /\.main-content \.service-main b\{font-size:14px/)
  assert.match(app, /workspace\.querySelector\('\.dashboard-shortcuts-panel'\)\?\.remove\(\)/)
  assert.match(styles, /\.dashboard-operation-summary-panel\{min-height:320px/)
  assert.match(styles, /\.main-content \.service-row \.status-pill\{font-size:11px;padding:7px 10px/)
  assert.match(styles, /\.metric-block:hover\{transform:translateY\(-3px\);box-shadow:/)
  assert.match(styles, /\.dashboard-timeline-item,.dashboard-attention-item,.dashboard-stage-card,\.dashboard-summary-metric\{transition:box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\),background \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row:hover\{transform:none;background:#fff;box-shadow:0 12px 26px rgba\(35,79,57,\.1\)/)
  assert.match(styles, /\.main-content \.dashboard-attention-item:hover\{transform:none;background:#fff;box-shadow:0 12px 26px rgba\(35,79,57,\.1\)/)
  assert.doesNotMatch(styles, /\.dashboard-stage-card:hover\{[^}]*transform:translateY\(/)
  assert.match(styles, /\.main-content \.dashboard-summary-metric:hover\{[^}]*transform:translateY\(-3px\)/)
  assert.doesNotMatch(styles, /\.dashboard-timeline-item:hover,.dashboard-attention-item:hover[^}]*translateX\(/)
  assert.match(styles, /\.attendance-summary>div\{transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\),box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.dashboard-paddock-row\{transition:box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\),background \.22s ease/)
  assert.match(styles, /\.dashboard-summary-service\{transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\),box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.service-price\{margin:7px 0;padding:16px 18px;border:1px solid var\(--line\);border-radius:18px/)
  assert.match(styles, /\.main-content \.dashboard-paddock-list\{gap:8px\}/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row\{padding:14px 16px;border:1px solid var\(--line\);border-radius:14px/)
  assert.match(styles, /\.main-content \.dashboard-attention-list\{gap:8px\}/)
  assert.match(styles, /\.main-content \.dashboard-attention-item\{padding:12px 14px;border:1px solid var\(--line\);border-radius:14px/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row::before\{content:"";position:absolute;inset:0;z-index:-1;border:1px solid var\(--line\);border-radius:14px;transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row:hover::before\{transform:translateY\(-3px\)/)
  assert.match(styles, /\.main-content \.dashboard-timeline-list\{gap:10px\}/)
  assert.match(styles, /\.main-content \.dashboard-timeline-item\{padding:14px 16px;border:1px solid #d5e3d9;border-radius:16px;background:#f3f8f4/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row::before\{display:none!important\}/)
  assert.match(styles, /\.main-content \.dashboard-attention-item::before\{display:none!important\}/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row,\.main-content \.dashboard-attention-item,\.main-content \.dashboard-summary-service,\.main-content \.dashboard-summary-metric\{position:relative;isolation:isolate;animation:none!important;transition:none!important;transform:none!important;box-shadow:none!important;background:transparent!important;border-color:transparent!important\}/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row::before,\.main-content \.dashboard-attention-item::before,\.main-content \.dashboard-summary-service::before,\.main-content \.dashboard-summary-metric::before\{content:"";position:absolute;inset:0;z-index:-1;pointer-events:none;border:1px solid var\(--line\);border-radius:14px;background:#fff;box-shadow:none;transform:none;transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\),box-shadow \.22s ease\}/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row:hover,\.main-content \.dashboard-attention-item:hover,\.main-content \.dashboard-summary-service:hover,\.main-content \.dashboard-summary-metric:hover\{transform:none!important;box-shadow:none!important;background:transparent!important;border-color:transparent!important\}/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row::before,\.main-content \.dashboard-attention-item::before,\.main-content \.dashboard-summary-service::before,\.main-content \.dashboard-summary-metric::before\{display:block!important\}/)
  assert.match(styles, /\.main-content \.dashboard-paddock-row:hover::before,\.main-content \.dashboard-attention-item:hover::before,\.main-content \.dashboard-summary-service:hover::before,\.main-content \.dashboard-summary-metric:hover::before\{transform:translateY\(-3px\);box-shadow:0 12px 26px rgba\(35,79,57,\.1\)\}/)
  assert.match(styles, /\.module-panel select[^}]*appearance:none/)
  assert.match(styles, /\.module-panel[^}]*border-radius:22px/)
  assert.match(quoteStyles, /\.quote-preview-modal \{[^}]*border-radius:\s*26px/)
  assert.match(quoteStyles, /\.quote-service-card \{[^}]*border-radius:\s*17px/)
  assert.match(clientUi, /section\.innerHTML = section\.innerHTML\.replace\('BASE DE RELACIONAMENTO', 'CLIENTES'\)/)
  assert.match(styles, /\.main-content \.client-summary\{display:grid;grid-template-columns:repeat\(3,1fr\);gap:12px;border:0/)
  assert.match(styles, /\.main-content \.client-summary>div[^}]*\{background:#fff/)
  assert.match(styles, /\.main-content \.client-summary>div\{[^}]*transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.main-content \.client-summary>div:hover\{transform:translateY\(-3px\);box-shadow:/)
  assert.match(styles, /\.main-content \.client-directory-heading\{border-radius:0;background:#f8f5ee/)
  assert.match(styles, /\.main-content \.module-panel,[^}]*\.main-content \.billing-summary-live>div\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content [^{]*\.metric-block[^}]*\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content\{--surface:#fff\}/)
  assert.match(styles, /\.main-content \.module-panel,\.main-content \.panel,\.main-content \.table-panel,\.main-content \.metric-block,\.main-content \.dashboard-panel,\.main-content \.employee-dashboard-panel,\.main-content \.employee-dashboard-metrics>div,\.main-content \.billing-summary-live>div\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content \.client-summary>div,\.main-content \.attendance-summary>div\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content \.agenda-toolbar,\.main-content \.agenda-form-panel\{background:#fff\}/)
  assert.match(styles, /\.main-content \.agenda-live-grid \.calendar-day\{background:#fff\}/)
})

test('configurações organiza conta, segurança e regras operacionais em uma central própria', () => {
  assert.match(app, /class="settings-shell"/)
  assert.match(app, /id="settings-password-form"/)
  assert.match(app, /id="settings-operational-form"/)
  assert.match(styles, /\.settings-hero\{[^}]*border-top:5px solid var\(--dashboard-forest\)/)
  assert.match(styles, /\.settings-layout\{display:grid/)
})

test('relatórios usa o mesmo painel operacional e hierarquia visual da visão geral', () => {
  assert.match(app, /class="report-dashboard"/)
  assert.match(app, /class="report-hero"/)
  assert.match(app, /class="report-metrics"/)
  assert.match(styles, /\.report-dashboard\{display:grid/)
  assert.match(styles, /\.report-hero\{[^}]*border-top:5px solid var\(--dashboard-forest\)/)
})

test('layout mobile preserva navegação, leitura e toque sem criar overflow horizontal', () => {
  assert.match(styles, /@media\(max-width:700px\)[\s\S]*?\.mobile-nav-toggle\{display:grid/)
  assert.match(styles, /@media\(max-width:700px\)[\s\S]*?\.page-section\{width:100%;padding:24px 14px 44px;overflow:hidden/)
  assert.match(styles, /@media\(max-width:700px\)[\s\S]*?\.topbar-actions\{gap:8px/)
  assert.match(styles, /@media\(max-width:700px\)[\s\S]*?\.attendance-tools \.primary-button,\.directory-toolbar \.primary-button\{min-height:44px/)
})

test('menu mobile tem camada própria de fechamento e sobrescreve o estado colapsado do topo', () => {
  assert.match(index, /id="mobile-nav-backdrop"/)
  assert.match(app, /mobile-nav-backdrop.*addEventListener\('click'/)
  assert.match(styles, /\.mobile-nav-backdrop\{display:none\}/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\.topbar-collapsed\{display:flex!important;height:60px!important/)
  assert.match(styles, /\.mobile-nav-backdrop\.visible\{display:block/)
})
