import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8')
const quoteStyles = await readFile(new URL('../quotes-preview.css', import.meta.url), 'utf8')
const app = await readFile(new URL('../app.js', import.meta.url), 'utf8')
const clientUi = await readFile(new URL('../src/client-live-ui.js', import.meta.url), 'utf8')

test('linguagem visual compartilhada evita controles quadrados e campos nativos quebrados', () => {
  assert.match(styles, /--radius-control:14px/)
  assert.match(styles, /\.app-shell>\.sidebar\{[^}]*background:#dceae1!important/)
  assert.match(styles, /\.main-content>\.topbar\{[^}]*background:#f5f8f5!important/)
  assert.match(styles, /\.app-shell>\.sidebar\.sidebar-olive\{[^}]*background:#2f3b32!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\{[^}]*background:transparent!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\{[^}]*height:58px!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\.topbar-collapsed\{[^}]*height:0!important/)
  assert.match(styles, /\.main-content>\.topbar\.topbar-integrated\.topbar-collapsed\{[^}]*backdrop-filter:none!important/)
  assert.match(styles, /\.topbar-collapsed \.topbar-actions\{display:none!important/)
  assert.match(styles, /\.main-content\{background:#f3f0e8;color:#27332d/)
  assert.match(styles, /\.main-content \.module-panel,\.main-content \.panel,\.main-content \.table-panel\{background:#fffdf8/)
  assert.match(styles, /\.main-content \.primary-button\{background:#59684d/)
  assert.match(styles, /\.main-content \.dashboard-agenda-item\{border-radius:14px;margin:2px 0;padding:14px 12px/)
  assert.match(styles, /\.main-content \.dashboard-agenda-item:hover\{background:transparent;box-shadow:none;transform:translateY\(-2px\)/)
  assert.doesNotMatch(styles, /\.main-content \.dashboard-agenda-item:hover \.dashboard-arrow\{transform:translateX\(3px\)/)
  assert.match(styles, /\.main-content \.service-row:hover\{background:transparent;transform:translateY\(-2px\);box-shadow:none/)
  assert.doesNotMatch(styles, /\.client-record:hover,.attendance-item:hover\{background:#f7fbf8;transform:translateX\(3px\)/)
  assert.match(styles, /\.main-content \.vehicle-mark\{width:40px;height:40px;border-radius:12px;background:#f4f0e6;border-color:#ded6c8/)
  assert.match(styles, /\.main-content \.vehicle-mark:before\{[^}]*background:transparent;border:1\.5px solid #59684d/)
  assert.match(styles, /\.main-content \.vehicle-mark:after\{left:11px;top:18px;width:18px;height:4px;border-radius:999px;background:#59684d;box-shadow:none/)
  assert.match(styles, /\.main-content \.vehicle-mark span\{left:15px;top:11px;width:9px;height:9px;border:1\.5px solid #59684d;border-radius:3px;transform:rotate\(45deg\)/)
  assert.match(app, /<button class="service-row" data-service-index="\$\{index\}"><div class="service-main">/)
  assert.match(styles, /\.main-content \.service-row\{grid-template-columns:1fr auto/)
  assert.match(styles, /\.main-content \.vehicle-mark\{display:none!important/)
  assert.match(styles, /\.main-content \.employee-dashboard-order\{grid-template-columns:minmax\(0,1fr\) auto 16px/)
  assert.match(quoteStyles, /\.quote-delete-button\s*\{[^}]*color:\s*#a24e4e/)
  assert.match(styles, /\.main-content \.service-row\{min-height:72px;padding:18px 16px/)
  assert.match(styles, /\.main-content \.service-main b\{font-size:14px/)
  assert.match(app, /workspace\.querySelector\('\.dashboard-shortcuts-panel'\)\?\.remove\(\)/)
  assert.match(styles, /\.dashboard-operation-summary-panel\{min-height:320px/)
  assert.match(styles, /\.main-content \.service-row \.status-pill\{font-size:11px;padding:7px 10px/)
  assert.match(styles, /\.metric-block:hover\{transform:translateY\(-3px\);box-shadow:/)
  assert.match(styles, /\.dashboard-timeline-item,.dashboard-attention-item,.dashboard-stage-card,\.dashboard-summary-metric\{transition:box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\),background \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.doesNotMatch(styles, /\.dashboard-attention-item:hover[^}]*transform:translateY\(/)
  assert.doesNotMatch(styles, /\.dashboard-stage-card:hover[^}]*transform:translateY\(/)
  assert.doesNotMatch(styles, /\.dashboard-summary-metric:hover[^}]*transform:translateY\(/)
  assert.doesNotMatch(styles, /\.dashboard-timeline-item:hover,.dashboard-attention-item:hover[^}]*translateX\(/)
  assert.match(styles, /\.attendance-summary>div\{transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\),box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.dashboard-paddock-row\{transition:box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\),background \.22s ease/)
  assert.match(styles, /\.dashboard-summary-service\{transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\),box-shadow \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.service-price\{margin:7px 0;padding:16px 18px;border:1px solid var\(--line\);border-radius:18px/)
  assert.doesNotMatch(styles, /\.main-content \.dashboard-paddock-row:hover\{transform:translateY\(/)
  assert.match(styles, /\.module-panel select[^}]*appearance:none/)
  assert.match(styles, /\.module-panel[^}]*border-radius:22px/)
  assert.match(quoteStyles, /\.quote-preview-modal \{[^}]*border-radius:\s*26px/)
  assert.match(quoteStyles, /\.quote-service-card \{[^}]*border-radius:\s*17px/)
  assert.match(clientUi, /section\.innerHTML = section\.innerHTML\.replace\('BASE DE RELACIONAMENTO', 'CLIENTES'\)/)
  assert.match(styles, /\.main-content \.client-summary\{display:grid;grid-template-columns:repeat\(3,1fr\);gap:12px;border:0/)
  assert.match(styles, /\.main-content \.client-summary>div[^}]*\{background:#fff/)
  assert.match(styles, /\.main-content \.client-summary>div\{[^}]*transition:transform \.22s cubic-bezier\(\.16,1,\.3,1\)/)
  assert.match(styles, /\.main-content \.client-summary>div:hover\{transform:translateY\(-3px\);box-shadow:/)
  assert.match(styles, /\.main-content \.client-directory-heading\{border-radius:0;background:#f8f5ee/)
  assert.match(styles, /\.main-content \.module-panel,[^}]*\.main-content \.billing-summary-live>div\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content [^{]*\.metric-block[^}]*\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content\{--surface:#fff\}/)
  assert.match(styles, /\.main-content \.module-panel,\.main-content \.panel,\.main-content \.table-panel,\.main-content \.metric-block,\.main-content \.dashboard-panel,\.main-content \.employee-dashboard-panel,\.main-content \.employee-dashboard-metrics>div,\.main-content \.billing-summary-live>div\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content \.client-summary>div,\.main-content \.attendance-summary>div\{background:#fff;border-color:var\(--line\)/)
  assert.match(styles, /\.main-content \.agenda-toolbar,\.main-content \.agenda-form-panel\{background:#fff\}/)
  assert.match(styles, /\.main-content \.agenda-live-grid \.calendar-day\{background:#fff\}/)
})
