import { buildAutomationControlState, buildFollowUpHistorySummary, buildMessageTemplatePreview, classifyFollowUp, groupFollowUps, renderMessageTemplate } from './post-sale-rules.js'

const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]))
const typeLabel = { check_in: 'Check-in', care_tip: 'Dica de cuidado', review: 'Avaliação', return: 'Lembrete de retorno' }
const statusLabel = { today: 'Hoje', overdue: 'Atrasado', upcoming: 'Próximo', done: 'Concluído' }
const eventLabel = { message_edited: 'Mensagem editada', scheduled: 'Automação programada', automation_disabled: 'Automação desativada', sent: 'Mensagem enviada', send_failed: 'Falha no envio', undone: 'Envio desfeito' }
const profile = () => globalThis.__sessionProfile

async function render(root) {
  root.innerHTML = '<div class="post-sale-loading">Carregando acompanhamentos…</div>'
  try {
    const items = await globalThis.__postSale.loadPostSaleFollowUps(profile())
    const templates = await globalThis.__postSale.ensureDefaultMessageTemplates(profile())
    const events = await globalThis.__postSale.loadPostSaleFollowUpEvents(profile(), items.map((item) => item.id))
    const eventsByFollowUp = new Map(items.map((item) => [item.id, events.filter((event) => event.follow_up_id === item.id)]))
    const now = new Date()
    const pending = items.filter((item) => item.status === 'pending')
    const counts = { today: pending.filter((item) => classifyFollowUp(item, now) === 'today').length, overdue: pending.filter((item) => classifyFollowUp(item, now) === 'overdue').length, upcoming: pending.filter((item) => classifyFollowUp(item, now) === 'upcoming').length }
    const metric = (title, value, copy, tone = '') => `<article class="post-sale-metric ${tone}"><span>${title}</span><b>${String(value).padStart(2, '0')}</b><small>${copy}</small></article>`
    const grouped = groupFollowUps(items)
    const cards = grouped.map((group, index) => {
      const first = group.items[0]
      const client = first.clients?.full_name || 'Cliente'
      const vehicle = [first.vehicles?.make, first.vehicles?.model, first.vehicles?.license_plate].filter(Boolean).join(' · ') || 'Veículo não informado'
      const latest = group.items.find((item) => item.status === 'pending') || group.items[0]
      const latestGroup = classifyFollowUp(latest, now)
      const details = group.items.map((item) => { const itemGroup = classifyFollowUp(item, now); const itemTemplates = templates.filter((template) => template.follow_up_type === item.follow_up_type); const options = itemTemplates.map((template) => `<option value="${template.id}" ${template.id === item.template_id ? 'selected' : ''}>${escapeHtml(template.name)}</option>`).join(''); const automationState = buildAutomationControlState(item); const automation = item.status === 'pending' ? `<div class="post-sale-automation"><label class="post-sale-automation-toggle" for="post-sale-auto-${item.id}"><input id="post-sale-auto-${item.id}" type="checkbox" data-post-sale-auto="${item.id}" ${automationState.enabled ? 'checked' : ''} /><span class="post-sale-switch" aria-hidden="true"></span><span>${automationState.label}</span></label><select data-post-sale-template="${item.id}">${options}</select><input type="datetime-local" data-post-sale-schedule="${item.id}" value="${escapeHtml(String(item.due_at || '').slice(0, 16))}" /><button class="text-button" data-post-sale-automation-save="${item.id}">Salvar automação</button></div>` : ''; const actions = item.status === 'pending' ? `<button class="outline-button" data-post-sale-edit="${item.id}">Editar mensagem</button><button class="primary-button" data-post-sale-send="${item.id}">Enviar pelo WhatsApp</button>` : `<button class="outline-button" data-post-sale-undo="${item.id}">Desfazer envio</button>`; const history = eventsByFollowUp.get(item.id) || []; const historySummary = buildFollowUpHistorySummary(history); const historyMarkup = `<details class="post-sale-history"><summary>${historySummary.label} <span>${historySummary.count}</span></summary><div class="post-sale-history-list">${history.length ? history.map((event) => `<div class="post-sale-history-item"><span>${escapeHtml(eventLabel[event.event_type] || event.event_type)}</span><time>${new Date(event.created_at).toLocaleString('pt-BR')}</time>${event.error_message ? `<small>${escapeHtml(event.error_message)}</small>` : ''}</div>`).join('') : '<small>Nenhuma movimentação registrada.</small>'}</div></details>`; return `<div class="post-sale-step"><div><span class="post-sale-step-dot ${itemGroup}"></span><div class="post-sale-step-copy"><b>${escapeHtml(typeLabel[item.follow_up_type] || item.follow_up_type)}</b><small data-post-sale-message="${item.id}">${new Date(item.due_at).toLocaleDateString('pt-BR')} · ${escapeHtml(item.message)}</small><textarea class="post-sale-message-editor hidden" data-post-sale-editor="${item.id}" rows="3">${escapeHtml(item.message)}</textarea>${automation}${historyMarkup}</div></div><div class="post-sale-step-actions">${actions}</div></div>` }).join('')
      return `<article class="post-sale-client-card"><button class="post-sale-client-summary" type="button" aria-expanded="false" data-post-sale-toggle="${index}"><span class="post-sale-client-avatar">${escapeHtml(client.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase())}</span><span class="post-sale-client-copy"><b>${escapeHtml(client)}</b><small>${escapeHtml(vehicle)}</small></span><span class="post-sale-client-progress"><strong>${group.pendingCount ? `${group.pendingCount} pendentes` : 'Tudo em dia'}</strong><small>${group.items.length} acompanhamentos · ${statusLabel[latestGroup]}</small></span><span class="post-sale-chevron">⌄</span></button><div class="post-sale-client-details hidden" data-post-sale-details="${index}">${details}</div></article>`
    }).join('') || '<div class="post-sale-empty"><b>Nenhum acompanhamento criado ainda</b><span>Quando um atendimento for concluído, os próximos contatos aparecerão aqui.</span></div>'
    const templateCards = templates.map((template, index) => { const preview = buildMessageTemplatePreview(template); return `<article class="post-sale-template-row" data-post-sale-template-row="${template.id}"><button class="post-sale-template-trigger" type="button" aria-expanded="false" data-post-sale-template-toggle="${template.id}"><span class="post-sale-template-index">${String(index + 1).padStart(2, '0')}</span><span class="post-sale-template-name"><b>${escapeHtml(template.name)}</b><small>${escapeHtml(typeLabel[template.follow_up_type] || template.follow_up_type)}</small></span><span class="post-sale-template-snippet">${escapeHtml(preview.message)}</span><span class="post-sale-template-chevron">⌄</span></button><form class="post-sale-template-editor hidden" data-post-sale-template-form="${template.id}"><label>Mensagem<textarea name="message" rows="3" required>${escapeHtml(template.message)}</textarea></label><div class="post-sale-template-editor-footer"><small>Use {{cliente}}, {{veiculo}} ou {{servico}} para personalizar.</small><button class="outline-button" type="submit">Salvar modelo</button></div></form></article>` }).join('')
    const firstPreview = buildMessageTemplatePreview(templates[0])
    root.innerHTML = `<div class="post-sale-summary">${metric('Para hoje', counts.today, 'contatos prioritários', 'today')}${metric('Atrasados', counts.overdue, 'precisam de retorno', 'overdue')}${metric('Próximos', counts.upcoming, 'já programados', 'upcoming')}</div><section class="module-panel post-sale-templates-panel"><div class="module-toolbar"><div><h2>Modelos de mensagem</h2><p class="muted">Edite os textos usados nos contatos automáticos. O servidor verifica a fila a cada minuto.</p></div><span class="status-pill in-progress">${templates.length} modelos</span></div><div class="post-sale-template-layout"><div class="post-sale-template-list">${templateCards}</div><aside class="post-sale-template-preview"><span class="post-sale-preview-label">Prévia da mensagem</span><b data-post-sale-preview-title>${escapeHtml(firstPreview.title)}</b><div class="post-sale-preview-window"><span class="post-sale-preview-contact">Cliente</span><p data-post-sale-preview-message>${escapeHtml(firstPreview.message)}</p><time>agora</time></div><small>A prévia usa valores de exemplo. Na fila, os dados reais do cliente substituem as variáveis.</small></aside></div></section><section class="module-panel post-sale-panel"><div class="module-toolbar"><div><h2>Clientes em acompanhamento</h2><p class="muted">Entre em um cliente para ver todas as próximas ações.</p></div><span class="status-pill in-progress">${grouped.length} clientes</span></div><div class="post-sale-list">${cards}</div></section>`
    root.querySelectorAll('.post-sale-automation-toggle input').forEach((input) => input.addEventListener('change', () => { const label = input.parentElement?.querySelector('span:last-child'); if (label) label.textContent = input.checked ? 'Envio automático ativo' : 'Ativar envio automático' }))
    const previewTitle = root.querySelector('[data-post-sale-preview-title]')
    const previewMessage = root.querySelector('[data-post-sale-preview-message]')
    root.querySelectorAll('[data-post-sale-template-toggle]').forEach((button) => button.addEventListener('click', () => { const row = button.closest('[data-post-sale-template-row]'); const editor = row?.querySelector('[data-post-sale-template-form]'); const expanded = button.getAttribute('aria-expanded') === 'true'; root.querySelectorAll('[data-post-sale-template-row]').forEach((otherRow) => { if (otherRow !== row) { otherRow.classList.remove('is-open'); otherRow.querySelector('[data-post-sale-template-toggle]')?.setAttribute('aria-expanded', 'false'); otherRow.querySelector('[data-post-sale-template-form]')?.classList.add('hidden') } }); button.setAttribute('aria-expanded', String(!expanded)); row?.classList.toggle('is-open', !expanded); editor?.classList.toggle('hidden', expanded); const template = templates.find((item) => item.id === button.dataset.postSaleTemplateToggle); if (template && !expanded) { const preview = buildMessageTemplatePreview(template); if (previewTitle) previewTitle.textContent = preview.title; if (previewMessage) previewMessage.textContent = preview.message } }))
    root.querySelectorAll('[data-post-sale-toggle]').forEach((button) => button.addEventListener('click', () => { const details = root.querySelector(`[data-post-sale-details="${button.dataset.postSaleToggle}"]`); const expanded = button.getAttribute('aria-expanded') === 'true'; button.setAttribute('aria-expanded', String(!expanded)); details.classList.toggle('hidden', expanded) }))
    const updateLocalFollowUp = (id, status) => { const current = items.find((item) => item.id === id); if (current) { current.status = status; current.sent_at = status === 'sent' ? new Date().toISOString() : null } globalThis.__postSaleFollowUps = items; document.dispatchEvent(new CustomEvent('post-sale-data-ready')) }
    root.querySelectorAll('[data-post-sale-template-form]').forEach((form) => form.addEventListener('submit', async (event) => { event.preventDefault(); const template = templates.find((item) => item.id === form.dataset.postSaleTemplateForm); if (!template) return; const button = form.querySelector('button'); button.disabled = true; try { await globalThis.__postSale.saveMessageTemplate(profile(), { id: template.id, followUpType: template.follow_up_type, name: template.name, message: form.elements.message.value }); template.message = form.elements.message.value.trim(); const snippet = form.closest('[data-post-sale-template-row]')?.querySelector('.post-sale-template-snippet'); if (snippet) snippet.textContent = template.message; const preview = buildMessageTemplatePreview(template); if (previewTitle?.textContent === template.name && previewMessage) previewMessage.textContent = preview.message; globalThis.showToast?.('Modelo de mensagem salvo.'); } catch (error) { globalThis.showToast?.(error.message) } finally { button.disabled = false } }))
    root.querySelectorAll('[data-post-sale-automation-save]').forEach((button) => button.addEventListener('click', async (event) => { event.stopPropagation(); const item = items.find((entry) => entry.id === button.dataset.postSaleAutomationSave); const templateId = root.querySelector(`[data-post-sale-template="${item.id}"]`)?.value || null; const autoSend = root.querySelector(`[data-post-sale-auto="${item.id}"]`)?.checked; const scheduledFor = root.querySelector(`[data-post-sale-schedule="${item.id}"]`)?.value; if (!item) return; button.disabled = true; try { const template = templates.find((entry) => entry.id === templateId); const context = { cliente: item.clients?.full_name || 'cliente', veiculo: [item.vehicles?.make, item.vehicles?.model].filter(Boolean).join(' ') || 'seu veículo', servico: item.work_orders?.service_description || 'serviço' }; const message = template ? renderMessageTemplate(template.message, context) : item.message; await globalThis.__postSale.updateFollowUp(profile(), item.id, 'pending', undefined, message); await globalThis.__postSale.setFollowUpAutomation(profile(), item.id, { autoSend, templateId, scheduledFor: scheduledFor ? new Date(scheduledFor).toISOString() : item.due_at }); item.message = message; item.auto_send = autoSend; item.template_id = templateId; item.due_at = scheduledFor ? new Date(scheduledFor).toISOString() : item.due_at; globalThis.__postSaleFollowUps = items; document.dispatchEvent(new CustomEvent('post-sale-data-ready')); globalThis.showToast?.(autoSend ? 'Automação ativada para este contato.' : 'Automação salva e desativada.'); await render(root) } catch (error) { button.disabled = false; globalThis.showToast?.(error.message) } }))
    root.querySelectorAll('[data-post-sale-edit]').forEach((button) => button.addEventListener('click', (event) => { event.stopPropagation(); const editor = root.querySelector(`[data-post-sale-editor="${button.dataset.postSaleEdit}"]`); const save = document.createElement('button'); save.type = 'button'; save.className = 'primary-button'; save.dataset.postSaleSave = button.dataset.postSaleEdit; save.textContent = 'Salvar mensagem'; button.replaceWith(save); editor?.classList.remove('hidden'); editor?.focus(); save.addEventListener('click', async (saveEvent) => { saveEvent.stopPropagation(); save.disabled = true; try { await globalThis.__postSale.updateFollowUp(profile(), save.dataset.postSaleSave, 'pending', undefined, editor.value); const current = items.find((item) => item.id === save.dataset.postSaleSave); if (current) current.message = editor.value.trim(); globalThis.__postSaleFollowUps = items; document.dispatchEvent(new CustomEvent('post-sale-data-ready')); globalThis.showToast?.('Mensagem salva.'); await render(root) } catch (error) { save.disabled = false; globalThis.showToast?.(error.message) } }) }))
    root.querySelectorAll('[data-post-sale-send]').forEach((button) => button.addEventListener('click', async (event) => { event.stopPropagation(); const item = items.find((entry) => entry.id === button.dataset.postSaleSend); const number = item?.clients?.phone; if (!number) { globalThis.showToast?.('Este cliente não possui WhatsApp cadastrado.'); return } if (!(await globalThis.__requestConfirmation?.('post-sale-send'))) return; button.disabled = true; try { const connection = await fetch('/api/whatsapp/connection'); const connectionData = await connection.json(); if (!connection.ok || !['open', 'connected'].includes(String(connectionData.state).toLowerCase())) throw new Error('O WhatsApp da empresa não está conectado.'); const response = await fetch('/api/whatsapp/send', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ number, text: item.message }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Não foi possível enviar a mensagem.'); await globalThis.__postSale.updateFollowUp(profile(), button.dataset.postSaleSend, 'sent', undefined, item.message); updateLocalFollowUp(button.dataset.postSaleSend, 'sent'); globalThis.showToast?.('Mensagem enviada pelo WhatsApp.'); await render(root) } catch (error) { await globalThis.__postSale.recordFollowUpEvent?.(profile(), { followUpId: button.dataset.postSaleSend, eventType: 'send_failed', channel: 'whatsapp', message: item?.message, errorMessage: error.message }).catch(() => {}); button.disabled = false; globalThis.showToast?.(error.message) } }))
    root.querySelectorAll('[data-post-sale-undo]').forEach((button) => button.addEventListener('click', async (event) => { event.stopPropagation(); if (!(await globalThis.__requestConfirmation?.('post-sale'))) return; button.disabled = true; try { await globalThis.__postSale.updateFollowUp(profile(), button.dataset.postSaleUndo, 'pending'); updateLocalFollowUp(button.dataset.postSaleUndo, 'pending'); globalThis.showToast?.('Envio cancelado. O acompanhamento voltou para pendente.'); await render(root) } catch (error) { button.disabled = false; globalThis.showToast?.(error.message) } }))
  } catch (error) { root.innerHTML = `<div class="post-sale-empty"><b>Não foi possível carregar o pós-venda</b><span>${escapeHtml(error.message)}</span></div>` }
}

globalThis.__renderPostSale = (root) => render(root)
