begin;

create extension if not exists pgcrypto;

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(), name text not null,
  document_number text, phone text, email text,
  timezone text not null default 'America/Sao_Paulo',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete restrict,
  full_name text not null, role text not null check (role in ('administrator','reception','employee')),
  active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(company_id,id)
);
create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict,
  full_name text not null, phone text, email text, document_number text, notes text, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,id)
);
create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(), company_id uuid not null, client_id uuid not null,
  make text not null, model text not null, model_year integer, color text, license_plate text, vin text, notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(company_id,id), unique(company_id,license_plate), unique(company_id,client_id,id),
  foreign key(company_id,client_id) references public.clients(company_id,id) on delete restrict
);
create table if not exists public.work_orders (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete restrict,
  client_id uuid not null, vehicle_id uuid not null, responsible_id uuid,
  order_number bigint generated by default as identity, status text not null default 'scheduled' check (status in ('scheduled','in_progress','awaiting_approval','completed','cancelled')),
  scheduled_at timestamptz, started_at timestamptz, completed_at timestamptz, service_description text not null,
  internal_description text, total_amount numeric(12,2) not null default 0 check(total_amount>=0), discount_amount numeric(12,2) not null default 0 check(discount_amount>=0),
  payment_status text not null default 'pending' check(payment_status in ('pending','partial','paid','waived')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(company_id,id), unique(company_id,order_number), unique(company_id,client_id,id),
  foreign key(company_id,client_id) references public.clients(company_id,id) on delete restrict,
  foreign key(company_id,client_id,vehicle_id) references public.vehicles(company_id,client_id,id) on delete restrict,
  foreign key(company_id,responsible_id) references public.profiles(company_id,id) on delete set null,
  check(discount_amount<=total_amount)
);
create table if not exists public.work_order_photos (
  id uuid primary key default gen_random_uuid(), company_id uuid not null, work_order_id uuid not null, uploaded_by uuid,
  storage_path text not null unique, photo_type text not null default 'other' check(photo_type in ('before','during','after','other')), caption text,
  created_at timestamptz not null default now(), unique(company_id,id),
  foreign key(company_id,work_order_id) references public.work_orders(company_id,id) on delete cascade,
  foreign key(company_id,uploaded_by) references public.profiles(company_id,id) on delete set null
);
create table if not exists public.work_order_notes (
  id uuid primary key default gen_random_uuid(), company_id uuid not null, work_order_id uuid not null, author_id uuid,
  body text not null, is_internal boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,id),
  foreign key(company_id,work_order_id) references public.work_orders(company_id,id) on delete cascade,
  foreign key(company_id,author_id) references public.profiles(company_id,id) on delete set null
);
create table if not exists public.work_order_stage_history (
  id uuid primary key default gen_random_uuid(), company_id uuid not null, work_order_id uuid not null, changed_by uuid,
  from_status text, to_status text not null, comment text, created_at timestamptz not null default now(), unique(company_id,id),
  foreign key(company_id,work_order_id) references public.work_orders(company_id,id) on delete cascade,
  foreign key(company_id,changed_by) references public.profiles(company_id,id) on delete set null
);
create table if not exists public.client_order_tokens (
  id uuid primary key default gen_random_uuid(), company_id uuid not null, client_id uuid not null, work_order_id uuid not null,
  token_hash text not null unique check(token_hash ~ '^[0-9a-f]{64}$'), expires_at timestamptz not null, revoked_at timestamptz, created_by uuid,
  created_at timestamptz not null default now(), unique(company_id,id),
  foreign key(company_id,client_id) references public.clients(company_id,id) on delete cascade,
  foreign key(company_id,client_id,work_order_id) references public.work_orders(company_id,client_id,id) on delete cascade,
  foreign key(company_id,created_by) references public.profiles(company_id,id) on delete set null
);

create index if not exists profiles_company_role_idx on public.profiles(company_id,role) where active;
create index if not exists clients_company_name_idx on public.clients(company_id,full_name);
create index if not exists vehicles_company_client_idx on public.vehicles(company_id,client_id);
create index if not exists work_orders_company_status_idx on public.work_orders(company_id,status,scheduled_at);
create index if not exists work_orders_company_responsible_idx on public.work_orders(company_id,responsible_id) where responsible_id is not null;
create index if not exists photos_company_order_idx on public.work_order_photos(company_id,work_order_id);
create index if not exists notes_company_order_idx on public.work_order_notes(company_id,work_order_id);
create index if not exists history_company_order_idx on public.work_order_stage_history(company_id,work_order_id,created_at desc);
create index if not exists tokens_active_idx on public.client_order_tokens(company_id,work_order_id,expires_at) where revoked_at is null;

revoke all on table public.companies,public.profiles,public.clients,public.vehicles,public.work_orders,public.work_order_photos,public.work_order_notes,public.work_order_stage_history,public.client_order_tokens from anon;
grant select,insert,update,delete on table public.companies,public.profiles,public.clients,public.vehicles,public.work_orders,public.work_order_photos,public.work_order_notes,public.work_order_stage_history,public.client_order_tokens to authenticated;
alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.vehicles enable row level security;
alter table public.work_orders enable row level security;
alter table public.work_order_photos enable row level security;
alter table public.work_order_notes enable row level security;
alter table public.work_order_stage_history enable row level security;
alter table public.client_order_tokens enable row level security;

create schema if not exists private;
create or replace function private.current_company_id() returns uuid language sql stable security definer set search_path=pg_catalog,public,private,pg_temp as $$ select company_id from public.profiles where id=(select auth.uid()) and active limit 1 $$;
create or replace function private.is_admin_or_reception(p_company_id uuid) returns boolean language sql stable security definer set search_path=pg_catalog,public,private,pg_temp as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and company_id=p_company_id and active and role in ('administrator','reception')) $$;
create or replace function private.is_administrator(p_company_id uuid) returns boolean language sql stable security definer set search_path=pg_catalog,public,private,pg_temp as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and company_id=p_company_id and active and role='administrator') $$;
revoke all on schema private from public;
revoke all on all functions in schema private from public;
grant usage on schema private to authenticated;
grant execute on function private.current_company_id() to authenticated;
grant execute on function private.is_admin_or_reception(uuid) to authenticated;
grant execute on function private.is_administrator(uuid) to authenticated;

create policy profiles_select_self on public.profiles for select to authenticated using(id=(select auth.uid()) or private.is_administrator(company_id));
create policy companies_select_member on public.companies for select to authenticated using(id=(select private.current_company_id()));
create policy companies_update_admin on public.companies for update to authenticated using(id=(select private.current_company_id()) and private.is_administrator(id)) with check(id=(select private.current_company_id()));
create policy clients_select_staff on public.clients for select to authenticated using(private.is_admin_or_reception(company_id) or exists(select 1 from public.work_orders o where o.company_id=clients.company_id and o.client_id=clients.id and o.responsible_id=(select auth.uid())));
create policy clients_insert_staff on public.clients for insert to authenticated with check(private.is_admin_or_reception(company_id));
create policy clients_update_staff on public.clients for update to authenticated using(private.is_admin_or_reception(company_id)) with check(private.is_admin_or_reception(company_id));
create policy clients_delete_staff on public.clients for delete to authenticated using(private.is_admin_or_reception(company_id));
create policy vehicles_select_staff on public.vehicles for select to authenticated using(private.is_admin_or_reception(company_id) or exists(select 1 from public.work_orders o where o.company_id=vehicles.company_id and o.vehicle_id=vehicles.id and o.responsible_id=(select auth.uid())));
create policy vehicles_insert_staff on public.vehicles for insert to authenticated with check(private.is_admin_or_reception(company_id));
create policy vehicles_update_staff on public.vehicles for update to authenticated using(private.is_admin_or_reception(company_id)) with check(private.is_admin_or_reception(company_id));
create policy vehicles_delete_staff on public.vehicles for delete to authenticated using(private.is_admin_or_reception(company_id));
create policy orders_select_admin_reception on public.work_orders for select to authenticated using(private.is_admin_or_reception(company_id));
create policy orders_select_employee on public.work_orders for select to authenticated using(company_id=(select private.current_company_id()) and responsible_id=(select auth.uid()));
create policy orders_insert_staff on public.work_orders for insert to authenticated with check(private.is_admin_or_reception(company_id));
create policy orders_update_admin_reception on public.work_orders for update to authenticated using(private.is_admin_or_reception(company_id)) with check(private.is_admin_or_reception(company_id));
create policy orders_update_employee on public.work_orders for update to authenticated using(company_id=(select private.current_company_id()) and responsible_id=(select auth.uid())) with check(company_id=(select private.current_company_id()) and responsible_id=(select auth.uid()));
create policy orders_delete_admin_reception on public.work_orders for delete to authenticated using(private.is_admin_or_reception(company_id));
create policy photos_select_staff on public.work_order_photos for select to authenticated using(private.is_admin_or_reception(company_id) or exists(select 1 from public.work_orders o where o.id=work_order_id and o.company_id=work_order_photos.company_id and o.responsible_id=(select auth.uid())));
create policy photos_insert_staff on public.work_order_photos for insert to authenticated with check(uploaded_by=(select auth.uid()));
create policy photos_delete_staff on public.work_order_photos for delete to authenticated using(uploaded_by=(select auth.uid()) or private.is_admin_or_reception(company_id));
create policy notes_select_staff on public.work_order_notes for select to authenticated using((not is_internal and private.is_admin_or_reception(company_id)) or (is_internal and private.is_admin_or_reception(company_id)) or exists(select 1 from public.work_orders o where o.id=work_order_id and o.company_id=work_order_notes.company_id and o.responsible_id=(select auth.uid())));
create policy notes_insert_staff on public.work_order_notes for insert to authenticated with check(author_id=(select auth.uid()));
create policy notes_update_author on public.work_order_notes for update to authenticated using(author_id=(select auth.uid())) with check(author_id=(select auth.uid()));
create policy notes_delete_staff on public.work_order_notes for delete to authenticated using(author_id=(select auth.uid()) or private.is_admin_or_reception(company_id));
create policy history_select_staff on public.work_order_stage_history for select to authenticated using(private.is_admin_or_reception(company_id) or exists(select 1 from public.work_orders o where o.id=work_order_id and o.company_id=work_order_stage_history.company_id and o.responsible_id=(select auth.uid())));
create policy history_insert_staff on public.work_order_stage_history for insert to authenticated with check(changed_by=(select auth.uid()));
create policy tokens_staff_select on public.client_order_tokens for select to authenticated using(private.is_admin_or_reception(company_id));
create policy tokens_staff_insert on public.client_order_tokens for insert to authenticated with check(created_by=(select auth.uid()) and private.is_admin_or_reception(company_id));
create policy tokens_staff_update on public.client_order_tokens for update to authenticated using(private.is_admin_or_reception(company_id)) with check(private.is_admin_or_reception(company_id));
create policy tokens_staff_delete on public.client_order_tokens for delete to authenticated using(private.is_admin_or_reception(company_id));

commit;
